ignore:
  - vulnerability: GHSA-9c47-m6qq-7p4h
    package:
      name: json5
      version: 10.3.10
    reason: >
      False positive. Yarn resolves json5 to 2.2.3
      Confirmed via `yarn why json5`. No runtime usage of 2.2.1
